### ISSUE TITLE
Add config options for rapidocr_onnxruntime

### ISSUE THREAD

**Issue by MadMenHitBooker** [SWHL/SWHL#3]
Hi,

Thanks for the library, it's exactly what i was looking for.
However it may have a bug.
For undocumented option __use_cuda__
If i create 

```python
engine = RapidOCR(
    use_angle_cls=True, 
    use_text_det=True,
    cls_use_cuda=True,
    det_use_cuda=True,
    rec_use_cuda=True,
...
```

It doesn't work as expected, since only det is recognized for using cuda

```python
det_dict = {k.split("det_")[1]: v for k, v in det_dict.items()}
```

I would like to simply use my own __config.yaml__, something like:

```python
RapidOCR(config_path='custom_config.yaml')
```

Can you look into that ?

**Comment by SWHL** [comment]
Can you open a same issue in the [RapidOCR](https://github.com/RapidAI/RapidOCR) repo?

In this repo, it is not appropriate to discuss this issue.
Thanks.

**Comment by MadMenHitBooker** [comment]
Ok sure

[https://github.com/RapidAI/RapidOCR/issues/104](url)
